add staging env for frontend

diff --git a/.github/workflows/cdkactions_build-and-deploy.yaml b/.github/workflows/cdkactions_build-and-deploy.yaml
--- a/.github/workflows/cdkactions_build-and-deploy.yaml
+++ b/.github/workflows/cdkactions_build-and-deploy.yaml
@@ -129,6 +129,76 @@ jobs:
           cache-to: type=local,dest=/tmp/.buildx-cache
           tags: pennlabs/penn-mobile-frontend:latest,pennlabs/penn-mobile-frontend:${{ github.sha }}
     needs: react-check
+  stage-frontend:
+    name: Stage frontend
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: docker/setup-qemu-action@v1
+      - uses: docker/setup-buildx-action@v1
+      - name: Cache Docker layers
+        uses: actions/cache@v2
+        with:
+          path: /tmp/.buildx-cache
+          key: buildx-publish-frontend
+      - uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build/Publish
+        uses: docker/build-push-action@v2
+        with:
+          context: frontend
+          file: frontend/Dockerfile
+          push: ${{ github.ref == 'refs/heads/feature/*' }}
+          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/penn-mobile-frontend-staging:latest
+          cache-to: type=local,dest=/tmp/.buildx-cache
+          tags: pennlabs/penn-mobile-frontend-staging:latest,pennlabs/penn-mobile-frontend-staging:${{ github.sha }}
+    needs: react-check
+  feature-deploy:
+    runs-on: ubuntu-latest
+    container:
+      image: pennlabs/helm-tools:39b60af248944898fcbc58d1fe5b0f1995420aef
+    if: github.ref == 'refs/heads/feature/*'
+    steps:
+      - uses: actions/checkout@v2
+      - name: Deploy
+        run: |-
+          aws eks --region us-east-1 update-kubeconfig --name production --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/kubectl
+
+          # get repo name (by removing owner/organization)
+          RELEASE_NAME=${REPOSITORY#*/}
+
+          # this specifies what tag of icarus to pull down
+          DEPLOY_TAG=$(yq r k8s/staging-values.yaml deploy_version)
+          if [ "$DEPLOY_TAG" = "null" ]; then
+              echo "Could not find deploy tag"
+              exit 1
+          fi
+
+          helm repo add pennlabs https://helm.pennlabs.org/
+          for i in {1..10}; do
+            # This is bash soup, but it'll do.
+            # 1. Attempt to install with helm
+            # 2. If this succeeds, exit with a success status code
+            # 3. If it fails, mark the command as succeeded so that '-e' doesn't kick us out
+            # 4. Wait 10s and try again
+            helm upgrade --install --atomic --set=image_tag=$IMAGE_TAG -f k8s/staging-values.yaml --version "${DEPLOY_TAG}" $RELEASE_NAME pennlabs/icarus && exit 0 || true
+            sleep 10s
+            echo "Retrying deploy for $i times"
+          done
+
+          # If we get here, all helm installs failed so our command should fail
+          exit 1
+        env:
+          IMAGE_TAG: ${{ github.sha }}
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.GH_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
+          DO_AUTH_TOKEN: ${{ secrets.DO_AUTH_TOKEN }}
+          REPOSITORY: ${{ github.repository }}
+    needs:
+      - stage-frontend
   deploy:
     runs-on: ubuntu-latest
     container:
